# --- !Ups

CREATE TABLE USERS (
  NAME varchar(255) NOT NULL,
  ROLE varchar(10) NOT NULL,
  BUDGET integer NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE PLAYERS (
  NAME varchar(255) NOT NULL,
  ROLE char(1) NOT NULL,
  VALUE integer NOT NULL,
  TEAM varchar(255) NOT NULL,
  USER varchar(255) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE EVENTS (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  EVENT VARCHAR(4096) NOT NULL,
  SAVE_POINT smallint NOT NULL,
  PRIMARY KEY (ID)
);


INSERT INTO USERS VALUES ('max', 'admin', 100);
INSERT INTO USERS VALUES ('gino', 'bidder', 100);

# --- !Downs

DROP TABLE USERS;
DROP TABLE PLAYERS;
DROP TABLE EVENTS;
